"""Empirical dynamic spectrum access benchmark environments.

This module provides executable reinforcement-learning environments for
single-agent dynamic spectrum access under realistic stochastic channel
occupancy, interference, non-stationarity, variable user load, noisy sensing,
and irregular decision intervals.

The benchmark is intentionally simulation-based in the scientific sense, but
all outcomes are generated by real environment dynamics and real training runs.
There are no hardcoded benchmark winners or scripted result tables.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, asdict
from typing import Deque, Dict, List, Tuple

import numpy as np


@dataclass
class EmpiricalDSAConfig:
    """Configuration for the empirical DSA benchmark environment."""

    scenario_name: str = "stationary"
    num_channels: int = 8
    num_background_users: int = 5
    history_len: int = 6
    max_steps: int = 64

    sensing_noise: float = 0.05
    observation_dropout: float = 0.0
    interference_scale: float = 1.0
    collision_penalty: float = 1.25
    success_reward_scale: float = 2.0
    idle_bias: float = 0.05

    dt_mode: str = "constant"  # constant, uniform, bimodal, oscillating
    dt_min: float = 0.5
    dt_max: float = 2.0
    dt_base: float = 1.0

    non_stationarity_strength: float = 0.0
    fairness_tracking: bool = True
    seed: int = 42

    def to_dict(self) -> Dict[str, float | int | str | bool]:
        return asdict(self)


class EmpiricalSpectrumEnv:
    """A real executable DSA environment with stochastic temporal dynamics.

    The agent controls one transmitter. Background users compete for channels.
    Channel occupancy, quality, and interference evolve over time according to
    Markovian and drifting processes whose rate depends on elapsed decision
    interval ``dt``.
    """

    _instance_counter = 0

    def __init__(self, config: EmpiricalDSAConfig):
        self.config = config
        self.instance_id = EmpiricalSpectrumEnv._instance_counter
        EmpiricalSpectrumEnv._instance_counter += 1
        self.base_seed = int(config.seed + self.instance_id)
        self.reset_count = 0
        self.rng = np.random.default_rng(self.base_seed)

        self.num_channels = config.num_channels
        self.history_len = config.history_len
        self.feature_dim = self.num_channels * 4 + 6
        self.action_dim = self.num_channels

        self.step_count = 0
        self.total_time = 0.0
        self.current_dt = config.dt_base

        self.base_busy = np.zeros(self.num_channels, dtype=np.float32)
        self.phase = np.zeros(self.num_channels, dtype=np.float32)
        self.channel_quality = np.zeros(self.num_channels, dtype=np.float32)
        self.primary_busy = np.zeros(self.num_channels, dtype=np.float32)
        self.interference = np.zeros(self.num_channels, dtype=np.float32)
        self.last_bg_load = np.zeros(self.num_channels, dtype=np.float32)

        self.last_action = 0
        self.last_reward = 0.0
        self.last_success = 0.0
        self.last_collision = 0.0

        self.obs_history: Deque[np.ndarray] = deque(maxlen=self.history_len)
        self.dt_history: Deque[float] = deque(maxlen=self.history_len)
        self.bg_user_success: np.ndarray = np.zeros(max(1, config.num_background_users), dtype=np.float32)

        self.episode_reward = 0.0
        self.episode_successes = 0
        self.episode_collisions = 0
        self.episode_utilization = 0.0
        self.episode_agent_actions: List[int] = []

        self._reset_latent_state()

    def _scenario_defaults(self) -> None:
        cfg = self.config
        if cfg.scenario_name == "stationary":
            cfg.non_stationarity_strength = 0.0
            cfg.interference_scale = 1.0
            cfg.sensing_noise = max(cfg.sensing_noise, 0.03)
        elif cfg.scenario_name == "non_stationary":
            cfg.non_stationarity_strength = max(cfg.non_stationarity_strength, 0.35)
            cfg.interference_scale = max(cfg.interference_scale, 1.1)
        elif cfg.scenario_name == "interference_heavy":
            cfg.non_stationarity_strength = max(cfg.non_stationarity_strength, 0.15)
            cfg.interference_scale = max(cfg.interference_scale, 1.6)
            cfg.collision_penalty = max(cfg.collision_penalty, 1.5)
        elif cfg.scenario_name == "noisy_partial":
            cfg.sensing_noise = max(cfg.sensing_noise, 0.18)
            cfg.observation_dropout = max(cfg.observation_dropout, 0.12)
            cfg.non_stationarity_strength = max(cfg.non_stationarity_strength, 0.2)
        elif cfg.scenario_name == "variable_dt":
            cfg.non_stationarity_strength = max(cfg.non_stationarity_strength, 0.25)
            cfg.dt_mode = "uniform"
            cfg.dt_min = min(cfg.dt_min, 0.2)
            cfg.dt_max = max(cfg.dt_max, 3.0)

    def _reset_latent_state(self) -> None:
        self._scenario_defaults()
        self.step_count = 0
        self.total_time = 0.0
        self.current_dt = self.config.dt_base

        self.base_busy = self.rng.uniform(0.15, 0.6, size=self.num_channels).astype(np.float32)
        self.phase = self.rng.uniform(0.0, 2.0 * np.pi, size=self.num_channels).astype(np.float32)
        self.channel_quality = self.rng.uniform(0.35, 0.95, size=self.num_channels).astype(np.float32)
        self.primary_busy = (self.rng.random(self.num_channels) < self.base_busy).astype(np.float32)
        self.interference = self.rng.uniform(0.05, 0.25, size=self.num_channels).astype(np.float32)
        self.last_bg_load = np.zeros(self.num_channels, dtype=np.float32)

        self.last_action = 0
        self.last_reward = 0.0
        self.last_success = 0.0
        self.last_collision = 0.0

        self.episode_reward = 0.0
        self.episode_successes = 0
        self.episode_collisions = 0
        self.episode_utilization = 0.0
        self.episode_agent_actions = []
        self.bg_user_success = np.zeros(max(1, self.config.num_background_users), dtype=np.float32)

        self.obs_history.clear()
        self.dt_history.clear()

    def _sample_dt(self) -> float:
        cfg = self.config
        if cfg.dt_mode == "constant":
            dt = cfg.dt_base
        elif cfg.dt_mode == "uniform":
            dt = self.rng.uniform(cfg.dt_min, cfg.dt_max)
        elif cfg.dt_mode == "bimodal":
            dt = cfg.dt_min if self.rng.random() < 0.5 else cfg.dt_max
        elif cfg.dt_mode == "oscillating":
            phase = 2.0 * np.pi * (self.step_count / max(1, cfg.max_steps))
            dt = cfg.dt_base + 0.5 * (cfg.dt_max - cfg.dt_min) * np.sin(phase)
            dt = float(np.clip(dt, cfg.dt_min, cfg.dt_max))
        else:
            dt = cfg.dt_base
        return float(np.clip(dt, cfg.dt_min, cfg.dt_max))

    def _target_busy_probs(self) -> np.ndarray:
        cfg = self.config
        if cfg.non_stationarity_strength <= 0:
            return self.base_busy.copy()

        harmonic = np.sin(0.07 * self.total_time + self.phase)
        drift = cfg.non_stationarity_strength * harmonic
        if cfg.scenario_name in {"interference_heavy", "non_stationary", "noisy_partial", "variable_dt"}:
            regime = 0.12 if (self.step_count // 16) % 2 == 1 else -0.08
        else:
            regime = 0.0
        target = self.base_busy + drift + regime
        return np.clip(target, 0.05, 0.95)

    def _update_latent_channels(self, dt: float) -> None:
        target_busy = self._target_busy_probs()
        adapt = 1.0 - np.exp(-0.6 * dt)
        self.base_busy = np.clip((1.0 - adapt) * self.base_busy + adapt * target_busy, 0.05, 0.95)
        self.primary_busy = (self.rng.random(self.num_channels) < self.base_busy).astype(np.float32)

        quality_target = 0.55 + 0.25 * np.sin(0.09 * self.total_time + self.phase / 2.0)
        quality_noise = self.rng.normal(0.0, 0.04 + 0.02 * self.config.non_stationarity_strength, size=self.num_channels)
        quality_adapt = 1.0 - np.exp(-0.45 * dt)
        self.channel_quality = np.clip(
            (1.0 - quality_adapt) * self.channel_quality + quality_adapt * quality_target + quality_noise,
            0.05,
            1.0,
        ).astype(np.float32)

        interference_target = (
            0.08
            + self.config.interference_scale * 0.45 * self.primary_busy
            + 0.12 * self.last_bg_load
        )
        if self.config.scenario_name == "interference_heavy":
            interference_target += 0.18
        interference_noise = self.rng.normal(0.0, 0.03, size=self.num_channels)
        int_adapt = 1.0 - np.exp(-0.8 * dt)
        self.interference = np.clip(
            (1.0 - int_adapt) * self.interference + int_adapt * interference_target + interference_noise,
            0.0,
            1.0,
        ).astype(np.float32)

    def _background_actions(self) -> np.ndarray:
        num_users = self.config.num_background_users
        if num_users <= 0:
            return np.array([], dtype=np.int64)

        busy_penalty = 1.5 * self.primary_busy
        base_score = self.channel_quality - self.interference - busy_penalty
        base_score = base_score.astype(np.float32)

        actions: List[int] = []
        for _ in range(num_users):
            noise = self.rng.normal(0.0, 0.18, size=self.num_channels)
            score = base_score + noise
            if self.config.scenario_name == "interference_heavy":
                best = int(np.argmax(base_score))
                score[best] += 0.25
            if self.rng.random() < 0.12:
                action = int(self.rng.integers(0, self.num_channels))
            else:
                action = int(np.argmax(score))
            actions.append(action)
        return np.asarray(actions, dtype=np.int64)

    def _sense_channels(self) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        sensed_busy = self.primary_busy.copy()
        flip_mask = self.rng.random(self.num_channels) < self.config.sensing_noise
        sensed_busy[flip_mask] = 1.0 - sensed_busy[flip_mask]

        sensed_interference = np.clip(
            self.interference + self.rng.normal(0.0, self.config.sensing_noise, size=self.num_channels),
            0.0,
            1.0,
        )
        sensed_quality = np.clip(
            self.channel_quality + self.rng.normal(0.0, self.config.sensing_noise, size=self.num_channels),
            0.0,
            1.0,
        )

        if self.config.observation_dropout > 0:
            drop_mask = self.rng.random(self.num_channels) < self.config.observation_dropout
            sensed_interference[drop_mask] *= 0.5
            sensed_quality[drop_mask] *= 0.5

        return sensed_busy.astype(np.float32), sensed_interference.astype(np.float32), sensed_quality.astype(np.float32)

    def _build_current_features(self) -> np.ndarray:
        sensed_busy, sensed_interference, sensed_quality = self._sense_channels()
        last_action_one_hot = np.zeros(self.num_channels, dtype=np.float32)
        last_action_one_hot[self.last_action] = 1.0

        denom = max(1, self.step_count)
        aux = np.array(
            [
                self.last_reward,
                self.last_success,
                self.last_collision,
                self.step_count / max(1, self.config.max_steps),
                self.config.num_background_users / max(1, self.num_channels),
                self.current_dt / max(self.config.dt_max, 1e-6),
            ],
            dtype=np.float32,
        )
        aux[0] = aux[0] / 3.0
        if denom > 0:
            aux[1] = self.episode_successes / denom
            aux[2] = self.episode_collisions / denom

        return np.concatenate(
            [sensed_busy, sensed_interference, sensed_quality, last_action_one_hot, aux],
            axis=0,
        ).astype(np.float32)

    def _state_dict(self) -> Dict[str, np.ndarray]:
        while len(self.obs_history) < self.history_len:
            self.obs_history.appendleft(np.zeros(self.feature_dim, dtype=np.float32))
        while len(self.dt_history) < self.history_len:
            self.dt_history.appendleft(self.current_dt)
        return {
            "obs": np.stack(list(self.obs_history), axis=0).astype(np.float32),
            "dt": np.asarray(list(self.dt_history), dtype=np.float32),
        }

    def reset(self, seed: int | None = None) -> Tuple[Dict[str, np.ndarray], Dict[str, float]]:
        if seed is not None:
            self.base_seed = int(seed)
            self.config.seed = int(seed)
            self.reset_count = 0
        self.rng = np.random.default_rng(self.base_seed + self.reset_count)
        self.reset_count += 1
        self._reset_latent_state()
        current = self._build_current_features()
        self.obs_history.append(current)
        self.dt_history.append(self.current_dt)
        return self._state_dict(), {
            "dt": self.current_dt,
            "scenario": self.config.scenario_name,
        }

    def step(self, action: int) -> Tuple[Dict[str, np.ndarray], float, bool, bool, Dict[str, float]]:
        action = int(np.clip(action, 0, self.num_channels - 1))
        dt = self.current_dt
        self.step_count += 1
        self.total_time += dt

        bg_actions = self._background_actions()
        self.last_bg_load = np.zeros(self.num_channels, dtype=np.float32)
        for bg_action in bg_actions:
            self.last_bg_load[bg_action] += 1.0
        if len(bg_actions) > 0:
            self.last_bg_load /= float(len(bg_actions))

        bg_collisions = int(np.sum(bg_actions == action))
        busy = bool(self.primary_busy[action] > 0.5)
        collision = busy or bg_collisions > 0

        throughput = float(self.channel_quality[action] * (1.0 - self.interference[action]))
        throughput = max(0.0, throughput)

        if collision:
            reward = -self.config.collision_penalty - 0.35 * busy - 0.2 * bg_collisions - 0.15 * float(self.interference[action])
            success = False
            self.episode_collisions += 1
        else:
            reward = self.config.idle_bias + self.config.success_reward_scale * throughput
            success = True
            self.episode_successes += 1
            self.episode_utilization += throughput

        self.episode_reward += reward
        self.last_reward = float(reward)
        self.last_success = float(success)
        self.last_collision = float(collision)
        self.last_action = action
        self.episode_agent_actions.append(action)

        if len(bg_actions) > 0:
            for i, bg_action in enumerate(bg_actions):
                bg_success = float((bg_action != action) and (self.primary_busy[bg_action] < 0.5))
                self.bg_user_success[i] += bg_success

        self.current_dt = self._sample_dt()
        self._update_latent_channels(dt=self.current_dt)

        current = self._build_current_features()
        self.obs_history.append(current)
        self.dt_history.append(self.current_dt)

        terminated = False
        truncated = self.step_count >= self.config.max_steps

        attempts = max(1, self.episode_successes + self.episode_collisions)
        info = {
            "success": float(success),
            "collision": float(collision),
            "throughput": throughput,
            "reward": float(reward),
            "dt": float(dt),
            "next_dt": float(self.current_dt),
            "busy": float(busy),
            "bg_collisions": float(bg_collisions),
            "spectrum_utilization": float(self.episode_utilization / max(1, self.step_count)),
            "collision_rate": float(self.episode_collisions / attempts),
            "success_rate": float(self.episode_successes / attempts),
            "num_background_users": float(self.config.num_background_users),
        }
        return self._state_dict(), float(reward), terminated, truncated, info

    def get_state_shape(self) -> Tuple[int, int]:
        return self.history_len, self.feature_dim

    def get_action_dim(self) -> int:
        return self.action_dim

    def get_metrics(self) -> Dict[str, float]:
        attempts = max(1, self.episode_successes + self.episode_collisions)
        action_hist = np.bincount(self.episode_agent_actions, minlength=self.num_channels).astype(np.float32)
        action_probs = action_hist / max(1.0, action_hist.sum())
        entropy = -np.sum(np.where(action_probs > 0, action_probs * np.log(action_probs + 1e-8), 0.0))

        fairness = 1.0
        if self.config.fairness_tracking and len(self.bg_user_success) > 0:
            x = self.bg_user_success + 1e-6
            fairness = float((x.sum() ** 2) / (len(x) * np.square(x).sum()))

        return {
            "episode_reward": float(self.episode_reward),
            "spectrum_utilization": float(self.episode_utilization / max(1, self.step_count)),
            "collision_rate": float(self.episode_collisions / attempts),
            "success_rate": float(self.episode_successes / attempts),
            "wall_clock_proxy_time": float(self.total_time),
            "policy_entropy": float(entropy),
            "background_fairness": fairness,
            "steps": float(self.step_count),
        }


class RandomHeuristic:
    """Uniform random channel-selection policy."""

    def __init__(self, action_dim: int, seed: int = 0):
        self.action_dim = action_dim
        self.rng = np.random.default_rng(seed)

    def act(self, state: Dict[str, np.ndarray]) -> int:
        return int(self.rng.integers(0, self.action_dim))


class GreedyOccupancyHeuristic:
    """Occupancy-aware greedy policy using the latest sensed observation."""

    def __init__(self, num_channels: int):
        self.num_channels = num_channels

    def act(self, state: Dict[str, np.ndarray]) -> int:
        latest = state["obs"][-1]
        n = self.num_channels
        sensed_busy = latest[:n]
        sensed_interference = latest[n : 2 * n]
        sensed_quality = latest[2 * n : 3 * n]
        score = (1.0 - sensed_busy) * sensed_quality - 0.7 * sensed_interference
        return int(np.argmax(score))


def make_empirical_suite(seed: int = 42) -> Dict[str, EmpiricalDSAConfig]:
    """Create the benchmark suite required for the empirical evaluation."""

    common = dict(num_channels=8, history_len=6, max_steps=64, seed=seed)
    return {
        "stationary": EmpiricalDSAConfig(scenario_name="stationary", num_background_users=4, **common),
        "non_stationary": EmpiricalDSAConfig(
            scenario_name="non_stationary",
            num_background_users=4,
            non_stationarity_strength=0.35,
            **common,
        ),
        "interference_heavy": EmpiricalDSAConfig(
            scenario_name="interference_heavy",
            num_background_users=7,
            interference_scale=1.6,
            **common,
        ),
        "varying_users_small": EmpiricalDSAConfig(scenario_name="stationary", num_background_users=2, **common),
        "varying_users_large": EmpiricalDSAConfig(scenario_name="stationary", num_background_users=8, **common),
        "noisy_partial": EmpiricalDSAConfig(
            scenario_name="noisy_partial",
            num_background_users=5,
            sensing_noise=0.2,
            observation_dropout=0.15,
            **common,
        ),
        "variable_dt": EmpiricalDSAConfig(
            scenario_name="variable_dt",
            num_background_users=5,
            dt_mode="uniform",
            dt_min=0.2,
            dt_max=3.0,
            non_stationarity_strength=0.25,
            **common,
        ),
    }
