#!/usr/bin/env python3
"""Generate ``RESULTS.md`` from ``results/``.  Nothing in it is written by hand.

Principle P1 in mechanical form: this script is the **only** way a metric enters
a prose document in this repository.  Every number below is read from a CSV
under ``results/tables/`` or from ``results/claims.json``; there is no literal
metric anywhere in this file.  CI regenerates ``RESULTS.md`` and runs
``git diff --exit-code`` on it, so a hand-edited result cannot survive a merge.

The report is deterministic: no timestamps, no wall-clock values, no run-order
dependence.  Two invocations against the same ``results/`` produce byte-identical
markdown.

Usage
-----
    python scripts/make_report.py
    python scripts/make_report.py --results-dir results --output RESULTS.md
    python scripts/make_report.py --check      # non-zero exit if the file is stale
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

import pandas as pd
import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from dsa.analysis.stats import NO_DIFFERENCE_PHRASE  # noqa: E402

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
DP = 3  # spec 4.5: three decimals in prose, never 17 significant digits


def f(x: object, dp: int = DP) -> str:
    """Format one number for prose.  Missing stays missing -- never zero."""
    try:
        v = float(x)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return str(x)
    if v != v:
        return "n/a"
    return f"{v:.{dp}f}"


def _table(frame: pd.DataFrame, columns: list[tuple[str, str]], dp: int = DP) -> list[str]:
    """Render selected columns as a markdown table, formatting floats."""
    present = [(src, title) for src, title in columns if src in frame.columns]
    lines = [
        "| " + " | ".join(t for _, t in present) + " |",
        "|" + "|".join("---" for _ in present) + "|",
    ]
    for _, row in frame.iterrows():
        cells = []
        for src, _ in present:
            value = row[src]
            if isinstance(value, (int,)) and not isinstance(value, bool):
                cells.append(str(value))
            elif isinstance(value, float):
                cells.append(f(value, dp))
            else:
                cells.append(str(value))
        lines.append("| " + " | ".join(cells) + " |")
    return lines


def _read(path: pathlib.Path) -> pd.DataFrame:
    return pd.read_csv(path) if path.exists() else pd.DataFrame()


def build_report(results_dir: pathlib.Path, prereg_path: pathlib.Path | None = None) -> str:
    tables_dir = results_dir / "tables"
    main = _read(tables_dir / "main_table.csv")
    ranking = _read(tables_dir / "overall_ranking.csv")
    comparisons = _read(tables_dir / "comparisons.csv")
    ablation = _read(tables_dir / "ablation.csv")
    learning = _read(tables_dir / "learning_check.csv")
    federated = _read(tables_dir / "federated_table.csv")
    budget = _read(tables_dir / "parameter_budget.csv")
    all_runs = _read(results_dir / "all_runs.csv")

    manifest_path = results_dir / "manifest.json"
    manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {}
    claims_path = results_dir / "claims.json"
    claims_doc = json.loads(claims_path.read_text()) if claims_path.exists() else {"claims": []}
    claims = {c["claim_id"]: c for c in claims_doc.get("claims", [])}

    # The alpha level and any other protocol constant quoted in prose are read
    # from the pre-registration file, never typed into this script.
    prereg: dict = {}
    prereg_path = prereg_path or (REPO_ROOT / "configs" / "preregistration.yaml")
    if prereg_path.exists():
        prereg = yaml.safe_load(prereg_path.read_text()) or {}

    L: list[str] = []
    add = L.append

    add("# Results")
    add("")
    add(
        "**This file is generated by `scripts/make_report.py` from the CSVs under "
        "`results/`. Do not edit it by hand — CI regenerates it and fails on any diff.** "
        "Every number below is read from a file in this repository; each is traceable to a "
        "`claim_id` in `results/claims.json`, which names the source CSV and column."
    )
    add("")

    # ------------------------------------------------------------ provenance #
    add("## Provenance")
    add("")
    matrix = manifest.get("matrix", {})
    versions = manifest.get("versions", {})
    rows = [
        ("git commit", manifest.get("git_commit", "unknown")),
        ("pre-registration sha256", manifest.get("preregistration_sha256", "unknown")),
        ("scenarios", ", ".join(matrix.get("scenarios", []))),
        ("models", ", ".join(matrix.get("models", []))),
        ("baselines", ", ".join(matrix.get("baselines", []))),
        ("seeds", str(len(matrix.get("seeds", [])))),
        ("training steps per run", str(matrix.get("training_steps", "n/a"))),
        ("evaluation episodes per run", str(matrix.get("eval_episodes", "n/a"))),
        ("rows in all_runs.csv", str(len(all_runs))),
        ("python / torch / numpy", f"{versions.get('python','?')} / {versions.get('torch','?')} / {versions.get('numpy','?')}"),
    ]
    add("| field | value |")
    add("|---|---|")
    for key, value in rows:
        add(f"| {key} | {value} |")
    add("")

    guard = manifest.get("guard") or {}
    if guard.get("applied"):
        add("> **Compute guard fired.** " + str(guard.get("note", "")))
        add(">")
        add(
            "> The seed count was not reduced. Statistical power is the one thing the "
            "budget is not permitted to buy back."
        )
        add("")

    # -------------------------------------------------- the primary question #
    add("## The pre-registered primary result")
    add("")
    primary = [c for cid, c in claims.items() if cid.startswith("CLAIM.PRIMARY.")]
    if primary:
        claim = primary[0]
        add(f"**Claim `{claim['claim_id']}`.** {claim['statement']}")
        add("")
        add(
            f"- mean paired difference: **{f(claim['value'])}** "
            f"(95% CI [{f(claim['ci_low'])}, {f(claim['ci_high'])}])"
        )
        add(f"- p = {f(claim['p_value'])}, Holm-adjusted p = {f(claim['holm_adjusted_p'])}")
        add(f"- verdict: `{claim['verdict']}`")
        add("")
        if claim["verdict"] == "no_detectable_difference":
            add(
                "> The confidence interval contains zero. At this budget this repository finds "
                "**no detectable benefit from continuous-time state updates under irregular "
                "decision intervals**. That is the result; it is not a negative to be explained "
                "away, and it is stated in the same font as everything else."
            )
        else:
            add(
                "> The interval excludes zero. Note that this is a single pre-registered "
                "comparison at one budget on one scenario, and that the arms differ in exactly "
                "one factor by construction."
            )
        add("")
    else:
        add(
            "The pre-registered primary comparison could not be computed from the runs present "
            "in `results/` — both of its arms must be in the matrix. No claim is made."
        )
        add("")

    # ------------------------------------------------------- overall ranking #
    if not ranking.empty:
        add("## Overall ranking")
        add("")
        add(
            "Pooled over scenarios, mean of the per-scenario means, with a 95% bootstrap "
            "interval over scenarios. **Every policy that ran appears here, including the "
            "zero-parameter heuristics.** There is no model filter anywhere in the analysis layer."
        )
        add("")
        L.extend(
            _table(
                ranking,
                [
                    ("rank", "rank"),
                    ("model", "model"),
                    ("mean_eval_return", "mean eval return"),
                    ("mean_eval_return_std", "sd"),
                    ("mean_eval_return_ci_low", "CI low"),
                    ("mean_eval_return_ci_high", "CI high"),
                    ("n_scenarios", "scenarios"),
                ],
            )
        )
        add("")
        heuristics = set(budget[budget.get("parameter_count", 0) == 0]["model"]) if not budget.empty else set()
        top = ranking.iloc[0]
        if str(top["model"]) in heuristics:
            add(
                f"> A zero-parameter heuristic (`{top['model']}`) is ranked first. Whatever else "
                "this benchmark measures, at this budget the learned policies did not beat a "
                "policy with no parameters."
            )
            add("")

    # --------------------------------------------------------- per scenario #
    if not main.empty:
        add("## Per-scenario results")
        add("")
        for scenario in sorted(main["scenario"].unique()):
            chunk = main[main["scenario"] == scenario].sort_values("rank_in_scenario")
            add(f"### `{scenario}`")
            add("")
            L.extend(
                _table(
                    chunk,
                    [
                        ("rank_in_scenario", "rank"),
                        ("model", "model"),
                        ("mean_eval_return", "mean eval return"),
                        ("mean_eval_return_std", "sd"),
                        ("mean_eval_return_ci_low", "CI low"),
                        ("mean_eval_return_ci_high", "CI high"),
                        ("mean_success_rate", "success"),
                        ("mean_collision_rate", "collision"),
                        ("n_seeds", "n"),
                    ],
                )
            )
            add("")

    # ------------------------------------------------------- learning check #
    if not learning.empty:
        add("## Did anything learn? (family F5)")
        add("")
        add(
            "Each model is evaluated twice on the **identical** evaluation stream: once with its "
            "freshly initialised weights and once after training. A model that does not beat its "
            "own initialisation has not learned, and the table says so."
        )
        add("")
        tested = learning[learning["trainable"].astype(bool)] if "trainable" in learning else learning
        L.extend(
            _table(
                tested,
                [
                    ("scenario", "scenario"),
                    ("model", "model"),
                    ("mean_eval_return_untrained", "untrained"),
                    ("mean_eval_return_trained", "trained"),
                    ("mean_improvement", "improvement"),
                    ("ci_low", "CI low"),
                    ("ci_high", "CI high"),
                    ("holm_adjusted_p", "Holm p"),
                    ("verdict", "verdict"),
                ],
            )
        )
        add("")
        if "learned" in tested.columns and len(tested):
            n_learned = int((tested["learned"] == True).sum())  # noqa: E712
            add(
                f"**{n_learned} of {len(tested)}** trainable (scenario, model) cells improved "
                "significantly over their own initialisation after Holm correction "
                "(`CLAIM.LEARN.count`)."
            )
            add("")
            if n_learned == 0:
                add(
                    "> No cell cleared the bar. At this budget the training procedure did not "
                    "measurably improve any model over its random initialisation. Every "
                    "architectural comparison below should be read in that light: comparing "
                    "architectures that have not learned compares initialisations."
                )
                add("")

    # ------------------------------------------------------------- ablation #
    if not ablation.empty:
        add("## Architectural ablation (families F3, F4)")
        add("")
        add(
            "F3 decomposes the hybrid the repository title names: `ppo_ltc_cfc` against each of "
            "its two single-cell components, differing in exactly one block. F4 is the "
            "dt-awareness contrast. Every row carries an interval — a difference whose interval "
            f"contains zero is reported as *{NO_DIFFERENCE_PHRASE}*, never as a gain."
        )
        add("")
        L.extend(
            _table(
                ablation,
                [
                    ("family", "family"),
                    ("scenario", "scenario"),
                    ("label_a", "arm A"),
                    ("label_b", "arm B"),
                    ("mean_difference", "A - B"),
                    ("ci_low", "CI low"),
                    ("ci_high", "CI high"),
                    ("p_value", "p"),
                    ("holm_adjusted_p", "Holm p"),
                    ("verdict", "verdict"),
                ],
            )
        )
        add("")

    # ------------------------------------------------------ all comparisons #
    if not comparisons.empty:
        add("## All pre-registered comparisons")
        add("")
        n_sig = int(comparisons["significant"].sum()) if "significant" in comparisons else 0
        # alpha is read from the pre-registration, never typed in here.
        alpha = (prereg or {}).get("alpha", "n/a")
        add(
            f"{len(comparisons)} comparisons across "
            f"{comparisons['family'].nunique()} pre-registered families; "
            f"**{n_sig}** survive Holm–Bonferroni correction within their family "
            f"at α = {alpha} (from `configs/preregistration.yaml`)."
        )
        add("")
        L.extend(
            _table(
                comparisons,
                [
                    ("family", "family"),
                    ("scenario", "scenario"),
                    ("label_a", "arm A"),
                    ("label_b", "arm B"),
                    ("n_pairs", "n"),
                    ("mean_difference", "A - B"),
                    ("ci_low", "CI low"),
                    ("ci_high", "CI high"),
                    ("p_value", "p"),
                    ("holm_adjusted_p", "Holm p"),
                    ("cliffs_delta", "Cliff's δ"),
                    ("verdict", "verdict"),
                ],
            )
        )
        add("")

    # ------------------------------------------------------------ federated #
    if not federated.empty:
        add("## Federated topology study (family F7)")
        add("")
        add(
            "Three topologies at **one** architecture, one scenario and strictly matched compute. "
            "The conclusion is about topology and is **not** evidence about architecture. "
            "`centralized` is a performance reference, not a communication baseline: it transmits "
            "no model parameters and its ledger totals are zero by construction."
        )
        add("")
        add(
            "All byte counts are measured from the actual tensors at the moment of transfer by "
            "`CommunicationLedger`. No script, table or document computes a byte count from a formula."
        )
        add("")
        L.extend(
            _table(
                federated,
                [
                    ("arm", "arm"),
                    ("mean_eval_return", "mean eval return"),
                    ("mean_eval_return_std", "sd"),
                    ("mean_eval_return_ci_low", "CI low"),
                    ("mean_eval_return_ci_high", "CI high"),
                    ("cloud_megabytes", "cloud MB"),
                    ("edge_local_megabytes", "edge-local MB"),
                    ("total_megabytes", "total MB"),
                    ("train_steps", "train steps"),
                    ("declared_train_steps", "declared"),
                    ("train_steps_match_declared", "matched"),
                ],
            )
        )
        add("")
        if {"train_steps", "declared_train_steps"} <= set(federated.columns):
            matched = bool((federated["train_steps"] == federated["declared_train_steps"]).all())
            add(
                f"Compute matching across arms: **{'exact' if matched else 'BROKEN'}** — every arm's "
                "`train_steps` is the sum of `total_env_steps` over every agent it actually trained."
            )
            add("")

    # ------------------------------------------------------ parameter budget #
    if not budget.empty:
        add("## Capacity matching")
        add("")
        spread_claim = claims.get("CLAIM.BUDGET.spread")
        if spread_claim:
            add(
                f"Hidden widths are **solved**, not chosen, so every model lands within a few "
                f"tenths of a percent of the same parameter target. Largest-to-smallest ratio "
                f"across the registry: **{f(spread_claim['value'])}** (`CLAIM.BUDGET.spread`). "
                "Capacity is therefore not a confound."
            )
            add("")
        L.extend(
            _table(
                budget,
                [
                    ("model", "model"),
                    ("family", "family"),
                    ("cell_kinds", "blocks"),
                    ("dt_aware", "dt in state update"),
                    ("hidden_dim", "H"),
                    ("parameter_count", "parameters"),
                    ("param_error_frac", "error vs target"),
                ],
                dp=4,
            )
        )
        add("")

    # ------------------------------------------------------------- integrity #
    add("## Integrity checks")
    add("")
    if "max_first_epoch_ratio_deviation" in all_runs.columns:
        worst = all_runs["max_first_epoch_ratio_deviation"].dropna()
        if len(worst):
            add(
                f"- **PPO first-epoch ratio.** Worst deviation across all runs: "
                f"`{float(worst.max()):.3e}`. On the first epoch of the first minibatch the "
                "recomputed log-probabilities must reproduce the rollout's own, so the "
                "importance ratio must be exactly 1. A non-trivial deviation would indicate a "
                "stale hidden state, live dropout, or a missing `eval()`/`train()` switch; "
                "`scripts/analyze.py` refuses to build this report if it ever exceeds 1e-3."
            )
    if "train_steps" in all_runs.columns and "declared_train_steps" in all_runs.columns:
        neural = all_runs[all_runs.get("is_trainable", True) == True]  # noqa: E712
        if len(neural):
            ok = bool((neural["train_steps"] == neural["declared_train_steps"]).all())
            add(
                f"- **Executed vs declared training steps.** {'All match' if ok else 'MISMATCH'}. "
                "`train_steps` is `agent.total_env_steps`, incremented by `num_envs` per vector "
                "step — it cannot be a config value copied into a column."
            )
    add(
        "- **Seeding.** Environment seeds are `blake2b(base_seed, scenario, role, index)` and "
        "deliberately exclude the model name, so every policy in a cell observed a byte-identical "
        "environment stream. Reordering `--models` or `--scenarios` cannot change a single metric."
    )
    add("")

    add("## How to reproduce")
    add("")
    add("```bash")
    add("make install")
    add("make suite       # the confirmatory matrix")
    add("make federated   # the topology study")
    add("make analyze     # tables, figures, claims.json")
    add("make report      # regenerates this file")
    add("```")
    add("")
    add(
        "`results/manifest.json` records the git commit, the exact command line, the full config "
        "contents, the sha256 of the pre-registration, the solved hidden dimensions and parameter "
        "counts, measured throughput, library versions and the sha256 of every committed CSV. "
        "That manifest — not committed weights — is the reproducibility anchor."
    )
    add("")

    return "\n".join(L).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--results-dir", type=pathlib.Path, default=REPO_ROOT / "results")
    parser.add_argument("--output", type=pathlib.Path, default=REPO_ROOT / "RESULTS.md")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the file is stale")
    args = parser.parse_args(argv)

    if not (args.results_dir / "all_runs.csv").exists():
        raise SystemExit(f"error: {args.results_dir / 'all_runs.csv'} not found. Run `make suite` first.")

    report = build_report(args.results_dir)

    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != report:
            print(f"error: {args.output} is stale. Run `make report` and commit it.", file=sys.stderr)
            return 1
        print(f"{args.output} is current")
        return 0

    args.output.write_text(report)
    print(f"wrote {args.output} ({len(report.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
